name: Publish Website to CPanel
on:
  push:
    branches:
      - master
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 2
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        ftp-server: ftp.works.spiderworks.co.in
        ftp-username: supalGit@works.spiderworks.co.in
        ftp-password: ${{ secrets.FTP_PASSWORD }}
